## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
matrix:
  fast_finish: true
#  allow_failures:
#    - julia: nightly
notifications:
  email: false
git:
  depth: 99999999
## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("DoubleFloats"); Pkg.test("DoubleFloats"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter"); using Documenter;'
  - julia -e 'cd(Pkg.dir("DoubleFloats")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("DoubleFloats")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
 
